# Generated by Django 5.0.2 on 2024-03-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('D', 'Dollar'), ('R', 'Ruble')], default='R', max_length=1),
        ),
    ]
